public class removeduplicate {
    public static String[] filter(String[] sameer,String[] bandar){
        int ls=sameer.length;
        int lb=bandar.length;
        String[] gaddar=new String[ls];
    int count=0;
    boolean found1=false;
    
    for(int i=0;i<ls;i++){
        found1=false;
        for(int j=0;j<lb;j++){
            if((sameer[i].compareTo(bandar[j])==0)){
                found1=true;
            }
        }
        if(!found1){
            gaddar[count]=sameer[i];
            count++;
        }else{
            sameer[i]="removed";
        }
    }
    return gaddar;
    }
    public static void main(String[] args){
        String[] sameer={"soniya_0172",
        "szupramk4",
        "_prince_sharma_448",
        "__puruuuu__",
        "riyajoshii24",
        "monu_thakur_002",
        "_radhikathakurr",
        "pri.yaaa_30",
        "kheralia_dharini1611",
        "shubhsingh_13",
        "mohit_chauhan_prajapati",
        "harkesh.yadavv",
        "vishaltomar_17",
        "nikhilxanand_",
        "vidushi.k23",
        "_ak.sharma_12",
        "aman_kuma_2556",
        "_priyanshgarg",
        "bad.al17",
        "sanj_anaarora479",
        "btw.its.nancy_",
        "j.varsha.00",
        "kanikaa._3",
        "catg9310",
        "fq_its_fagun",
        "itz_me_shreya29",
        "s.yed.ahmed",
        "raobrijesh_28",
        "gunjan_pande5704",
        "shashi_mallick",
        "shiv_amkaushik7",
        "_25_ravi_ranjan",
        "akshat1115",
        "mutant_8383",
        "_nida.naiyer_",
        "night14crawler",
        "nt.yur.type",
        "priyadailla",
        "nikhilaggarwal2384",
        "mayank_solanki_____",
        "yash_kuhad23",
        "___jeet__gupta_",
        "_naira_kansal_",
        "aawaara.huuu.vai",
        "prakazhdiv",
        "saraswatmradul70",
        "6901.deepak001",
        "vansh_aggarwal17",
        "i_.dead",
        "aiyaz__ma",
        "_20yatinsingh",
        "a.m_meena_ji0466",
        "ali_faisal_alam_2",
        "mr_faheem_173",
        "shyam_aprasad8566",
        "kartikkk.goyal",
        "coc_giveaway00",
        "alex_tv_k",
        "heyy.aahana_",
        "delhi_jain_confessions",
        "alomgir420420",
        "adityagaur_05",
        "bitthal2004",
        "lakhmi615",
        "i.am.sndp",
        "_scartic_",
        "built_to_thrive_365",
        "_ravikumar.00",
        "div_v.ya",
        "mahak_jain2004",
        "_.ayushjoshi._",
        "arjavjain_2494",
        "priya_pp_14",
        "chauhan__.ayush",
        "naveen____thakur",
        "guptashivam43362",
        "__dhruvgulia__",
        "yadav_jii_043",
        "shivam9231gupta",
        "anmolgureja1234",
        "divyamj26",
        "neginikhil424",
        "shantanufff",
        "anil3433",
        "vaishnav.premsukh",
        "arba.z4016",
        "inikhilsingh2.0",
        "cmohanboro",
        "rahulkashyap6434",
        "warlockclashingfanpage",
        "sinister.ab",
        "itsjust.komal",
        "_free_gold_pass_",
        "anshika_solankii",
        "aayush_guptaa_",
        "gauravbhardwaj788",
        "flanshukundara",
        "prac_ticalaccounts",
        "nav_neet60",
        "_mnprett",
        "tanishq_in_chains",
        "mr_goku_0007",
        "arjavjain_24094",
        "sonuraj6180",
        "your_brother.ss",
        "theentertainmentzone0",
        "meena_ji_gourav",
        "abhinavmishra_420",
        "sandeepkr_018",
        "smazy.adarsh",
        "ab.hisheksharma893",
        "naveengupta00007",
        "ashish__0872",
        "pratham6748",
        "memer_excellence",
        "khshdb7e7e",
        "deshwalhunesh00",
        "wizardds9",
        "_mr.gupta_02",
        "bssaini1984",
        "vinay.gaur06",
        "amanjot9408",
        "111mohdaleem",
        "ad.bhardwaj_",
        "_mayankkk1",
        "akkhh_ii",
        "_.atulsingh2114",
        "mr_nillu_2025",
        "bhudev_ka_samrajya",
        "briar_boyle_swho",
        "sutton_benson_guan",
        "meena_ji_rajnish_",
        "sahilmeena153",
        "kheraliabhumi",
        "bhavbharatsinghal",
        "khan.aqbal.1",
        "ajnishr",
        "alkamachau",
        "samkhan5395",
        "harshan62",
        "p1_doglovers",
        "roshangupta5948",
        "deepsing_uin",
        "__clashroyalefreegems__",
        "im.mayankarya",
        "_kumauni_",
        "incredible_dytto_612",
        "bhaviksngh",
        "fire_man_fighter",
        "ayaramin",
        "kanashiikage",
        "_mridul_04"
        };
        String[] bandar={"dragon ballz editz","monu_thakur_002","naveen thakur","kanashiikage","sameer_bhardwaj","shantanufff",

        "white paper",
        "nt.yur.type",
        "shreya singh3003",
        "built to_thrive_365",
        "nida.naiyer",
        "im.mayankarya",
        "uch.i.h.a_m.a.d.ara_",
        "saraswatmradul70",
        "s.yed.ahmed","Idead",
        "scartic",
        "krishna_rastog",
        "gauravbhardwaj788",
        "otaku_bandar",
        "_20yatinsingh",
        "kunal_editz 005",
        "trustyjusty86",
        "6901.deepak001",
        "sharmashiv987",
        "amanadhikari29",
        "genjimok21",
        "aka deevanshika24","the.naveen9",
        "anime.aesthetics106",
        "xr_trushna_x",
        "tobikamy",
        "kunalthapa16",
        "daniyalhaseeb01",
        "abbas sohail",
        "_heart_hacker_dk",
        "abhishek.in",
        "confused_yt.42",
        "karande.pratap",
        "vyshnavi_dancer01","vyshu_offl",
        
        "slangcrystal",
        "thanu",
        "prashant sona","madhu_46",
        "dayas tojo",
        "tamanashsarkar_98",
        "ghost 070","sayeed awais",
        "mr_obito_jeevan","the_king_of_curses.",
        "aalsi beast",
        "_Lshaa_ww",
        "duhh.itz bipil","bipil",
        "musical lover since. 20","yuuichi katagiri 01",
        "yuuichi",
        "aayush.more_07","rishit_0.2",
        "maharshirevanth",
        "anonymous. world2425","anonymous",
        "sister_is_my_heart que..","itachi","uchiha_mathava","nihxlll0",
        "ta.manihar",
        "khadeem 144",
        "khushibhagat04",
        "wtf_kishan_",
        "abhi_z_x_judo",
        "kavi 07",
        
        "jd chandu",
        
        "iam khan_",
        "heart_ticker_nani_07",
        "yankio nguly",
        "nithish xa",
        "iam_jaydhvaj",
        "bitthal2004",
        
        "faizalkhan.22",
        
        "ritesh rathod_799",
        "rushikesh.pardhi.005",
        "that nonlyabi","akatsuki._.26",
        "legend_kishor_",
        "notty_hartik",
        "anish yadav 009",
        "orenonawaaadhi","mr_unique_one_009",
        "krrohith_5",
        "mr","king 2.0",
        "abhinavojha0",
        "imra.nansari4","it_zr_ishi",
        "a.s.h.i.s.h099",
        "gucci girl4444",
        "prem kumar 03",
        "Itz tarun sd",
        "anurag singh121",
        "urfav_weev_",
        "_honestly.aviii",
        "vignan 7",
        "dibyadarshan_hindu",
        "neeraj_._katoch",
        "yuvraj since2001",
        "akash.02",
        "tharigmd",
        "mr_broken_soul_09_13",
        "raghupathi_rao poladi",
        "m_a_y_u_r_t_h_a_k_o_r",
        "aaashiikk",
        
        
        
        "shadow 00.8",
        
        "gokula krishnan_2000"
        };
        String[] gaddar=filter(sameer,bandar);
        for(int i=0;i<gaddar.length;i++){
            System.out.println(gaddar[i]+" ");
        }

    }
}
